Jenkinsfile, aws/Full-PAS-Deployment.json, aws/PAS-Component-Single-Deployment.json, azure/README.md, azure/nested/psmp-nested-template.json
Fix script path inside psmp-nested-template
=> [Hotfix] cli-442 psmp nested template points to wrong script location

DRVault-Single-Deployment.json, Full-PAS-Deployment.json, PAS-AIO-dr-Deployment.json, PAS-AIO-template.json, PAS-Component-Single-Deployment.json, Vault-Single-Deployment.json
- Support "partition" in arns
- Add region to s3 buckets
=> Add support for gov Cloud

aws/DRVault-Single-Deployment.json, aws/Full-PAS-Deployment.json, aws/PAS-AIO-dr-Deployment.json, aws/PAS-AIO-template.json, aws/PAS-Component-Single-Deployment.json, aws/Vault-Single-Deployment.json
- Support for Partition
- CFN-Signal at the end of each sequence
=> Merge changes from govcloud to develop

aws/DRVault-Single-Deployment.json, aws/Full-PAS-Deployment.json, aws/PAS-AIO-dr-Deployment.json, aws/PAS-AIO-template.json, aws/PAS-Component-Single-Deployment.json, aws/Vault-Single-Deployment.json
- Tested by deployment and PVWA dashboard
=> CLI-530: Fetch vault password from SSM instead of S3

aws/DRVault-Single-Deployment.json, aws/Full-PAS-Deployment.json, aws/PAS-AIO-dr-Deployment.json, aws/PAS-AIO-template.json, aws/PAS-Component-Single-Deployment.json, aws/Vault-Single-Deployment.json
- Removed store of password in S3 bucket
=> CLI-531: As a devops I would like to store vault credentials in SSM only

azure/pas-hybrid-network.json, azure/pas-single-component-deploy-in-customer-network.json, azure/pas-single-component-deploy-in-pas-hybrid-network.json
- Fixed templates to generate guid correctly.
- Added PVWA FQDN to template parameters.
- Opened Outgoing Access on Security Group to All.
- Make sure web subnet is created vefore components subnet to prevent conflicts.
=> V10.7 azure

azure/import-pas-images.ps1
- Updated version to 10.8
- Added handling of VaultSAS
=> - Added handling of VaultSAS

aws/PAS-network-environment-NAT.json, aws/PAS-network-environment-PrivateLink.json, tests/aws/test_PAS-network-environment-NAT.py, tests/aws/test_PAS-network-environment-PrivateLink.py
adding pta sg to network templates
=> Update network templates with PTA

azure/import-pas-images.ps1
- Add optional parameters
- Allow importing several components
=> - Add optional parameters

aws/PAS-AIO-template.json
* - fix aio pvwahostname bug
* - fix installation order, PVWA first
* - fix installation order, PVWA first
* - fixed and tested(health check)
=> Fix aio issue (#142)

azure/README.md, azure/nested/psmp-nested-template.json, azure/pas-single-component-deploy-in-customer-network.json, azure/pas-single-component-deploy-in-pas-hybrid-network.json
Description: Hi All. I deployed the vault and now trying to deploy PVWA but giving this error.  Using 11.2 SASurl.
Error attached. 
{
"telemetryId": "ed3f46f1-2092-4445-b83c-73d53f226045",
"bladeInstanceId": "Blade_bc027eb69d014427830c9138113d4ea2_0_0",
"galleryItemId": "Microsoft.Template",
"createBlade": "DeployToAzure",
"code": "InvalidTemplate",
"message": "Deployment template validation failed: 'The template reference 'GuidGenerator' is not valid: could not find template resource or resource copy with this name. Please see https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_arm-2Dtemplate-2Dexpressions_-23reference&d=DwICaQ&c=E55fojPA83XrPGfndbiaQQ&r=SE43VVdDtD0uu4uNEwwOmfgMKzko-SiF1-Q3rViDTP4&m=5c169UEcfaHK39HETQR6CVDh7FrFOF-hn2F9MEMX4Ts&s=vDWljBwSH03l4jNn4WHjqSOJ6g4REWQoueTz …
=> - Fix missing GUID in template issue

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PAS-network-environment-PrivateLink.json, aws/Vault-Single-Deployment.yaml, tests/aws/test_PAS-network-environment-PrivateLink.py
reopened the PR. no changes were made since last approval
=> Aws new network privatelink

azure/nested/psmp-nested-template-v11.5.json, azure/pas-single-component-deploy.json, azure/pas-vault-deploy.json
all changes in pas-single-component-deploy.json are made by azure template editor
=> Rel 11.5 - azure

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
Resolves #[relevant GitHub issues, eg 76]
=> Release v12.0

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> Release v12.1

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PTA-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> Release v12.2

README.md, tests/requirements.txt
=> Readme patch

aws/PTA-Single-Deployment.yaml
=> Release v12.2.3

CHANGELOG.md, LICENSE.md, README.md, aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PTA-Single-Deployment.yaml, aws/README.md, aws/Vault-Single-Deployment.yaml, azure/README.md, azure/import-pas-images.ps1
=> version selection

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PTA-Single-Deployment.yaml
=>  Release v12.2 psmp rhel 8

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml, azure/README.md
=> Release v12.2 psmp rhel8

aws/PTA-Single-Deployment.yaml, tests/aws/test_PAS-network-environment-NAT.py, tests/aws/test_PAS-network-environment-PrivateLink.py
=> 12.6-branch to develop

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PTA-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
This should be merged to master and v12.6
=> make version static and remove selections

aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> adding hostname limitations

aws/PTA-Single-Deployment.yaml
=> remove bucket creation and use partition param

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
set full path for cfn-signal.exe
=> set full path for cfn-signal.exe

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PAS-network-environment-NAT.json, aws/PAS-network-environment-PrivateLink.json
change "PSM SSH Proxy" to "PSMP"
=> change "PSM SSH Proxy" to "PSMP"

aws/PTA-Single-Deployment.yaml, azure/README.md, azure/import-pas-images.ps1
=> Release v13.0

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PTA-Single-Deployment.yaml
align cfn-init and cfn-signal paths in linux
=> align cfn-init and cfn-signal paths in linux

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/PAS-network-environment-NAT.json, aws/PAS-network-environment-PrivateLink.json, tests/aws/test_PAS-network-environment-NAT.py, tests/aws/test_PAS-network-environment-PrivateLink.py
=> align PSMSSH with PSMP

azure/pas-full-network.json
=> fix psmp misconfiguration

azure/pas-full-network.json
Azure - split user and administrative access
=> Azure - split user and administrative access

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> allow hostname change for all templates

azure/nested/psmp-nested-template-hybrid.json, azure/nested/psmp-nested-template.json, azure/pas-dr-deploy.json, azure/pas-pta-deploy.json, azure/pas-single-component-deploy.json, azure/pas-vault-deploy.json
POC-100 - azure support non-zone regions
=> POC-100 - azure support non-zone regions

aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> Ec2 timeout

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml, azure/README.md, azure/import-pas-images.ps1, azure/pas-single-component-deploy-in-pas-hybrid-network.json, azure/pas-single-component-deploy.json
=> Release v13.2

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> POC-567: Fix VaultIpAddress for psmp

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml, azure/pas-dr-deploy.json, azure/pas-pta-deploy.json, azure/pas-vault-deploy.json
=> POC-566: Update allowed vm sizes

LICENSE.md, README.md, aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> POC-569: Add missing route53 code

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> POC-584: Update lambdas runtime

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml, azure/README.md
=> merge Develop

CHANGELOG.md, aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, azure/import-pas-images.ps1
=> POC-512: Update to RHEL 9

.github/workflows/update_url.yml
=> POC-634: Create GitHub Action

aws/DRVault-Single-Deployment.yaml, aws/Full-PAS-Deployment.yaml, aws/PAS-AIO-DR-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml, aws/Vault-Single-Deployment.yaml
=> POC-620: Remove route53 usage

aws/Full-PAS-Deployment.yaml
=> POC-720: Apply to FullPAS

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> POC-748: New userdata for linux components

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> SHPVWA-16535: Remove SetLocalService for PVWA

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> POC-917: Add PSM Hardening

aws/Full-PAS-Deployment.yaml, aws/PAS-Component-Single-Deployment.yaml
=> POC-1055: Add PVWAPrivateIP for cpm
